feat_forgot_password_controller
NewShiftStudio/gour-api-gateway pull request #22
Opened 2022-09-12 16:21 UTC by avorokhta

2022-09-13 08:41 UTC, mirageN1349 requested changes

2022-09-13 08:41 UTC, mirageN1349 commented on src/features/auth/dto/forgot-password.dto.ts
> +  login: string;
У нас же вроде бы везде email. Почему login string?

2022-09-13 10:27 UTC, avorokhta commented on src/features/auth/dto/forgot-password.dto.ts
> +  login: string;
dto регистрации

<img width="397" alt="Снимок экрана 2022-09-13 в 13 25 35" src="https://user-images.githubusercontent.com/93992220/189878162-84ed3230-62b6-4c3c-a694-191dfb8038e5.png">

изначально так было, при записи в бд всё заносится в поле login, даже если передан email

2022-09-13 10:30 UTC, mirageN1349 commented on src/features/auth/dto/forgot-password.dto.ts
> +  login: string;
> так изначально было передавался либо login, либо email при записи в бд всё заносится в поле login, даже если передан email

Но я бы в будущем переделал на emai все, пока не нужно

2022-09-14 08:07 UTC, avorokhta commented on src/features/auth/dto/forgot-password.dto.ts
> +  login: string;
> > так изначально было передавался либо login, либо email при записи в бд всё заносится в поле login, даже если передан email
> 
> Но я бы в будущем переделал на email все, пока не нужно

ок, думаю это просто будет

2022-09-20 22:49 UTC, mirageN1349 approved these changes

2022-09-20 22:49 UTC, merged