fix: 🐛 дто на смену аватара
NewShiftStudio/gour-api-gateway pull request #52
Opened 2022-11-01 13:53 UTC by avorokhta

2022-11-01 13:53 UTC, mirageN1349 commented
Task linked: [CU-32bfmg2 Нельзя удалить аватарку в личном кабинете](https://app.clickup.com/t/32bfmg2)

2022-11-24 07:47 UTC, mirageN1349 requested changes

2022-11-24 07:47 UTC, mirageN1349 commented on src/features/client-auth/dto/change-avatar.dto.ts
> +  @IsOptional()
А тут может не быть id?

2022-11-25 09:59 UTC, avorokhta commented on src/features/client-auth/dto/change-avatar.dto.ts
> +  @IsOptional()
он может быть null, тогда фото удалится из бд

2022-12-12 11:30 UTC, merged