fix: 🐛 данные для создания и редактирования товаров
NewShiftStudio/gour-api-gateway pull request #69
Opened 2022-11-22 14:34 UTC by avorokhta

2022-11-22 14:34 UTC, mirageN1349 commented
Task linked: [TSX-4533 Привести цены на проекте к единому виду](https://app.clickup.com/t/4712744/TSX-4533)

2022-11-24 07:43 UTC, mirageN1349 requested changes

2022-11-24 07:43 UTC, mirageN1349 commented on src/features/product/product.controller.ts
> +    console.log(dto);
log

2022-11-25 09:52 UTC, avorokhta commented on src/features/product/product.controller.ts
> +    console.log(dto);
в другом ПРе убрал

2022-12-12 11:30 UTC, merged